spring.application.name=identity-service
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=identity-service
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s

spring.datasource.url=jdbc:postgresql://localhost:5432/identity_db
spring.datasource.username=postgres
spring.datasource.password=020123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# En production, utiliser 'validate' avec Flyway/Liquibase
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/Nexus3PL

server.port=8081

# Configuration Keycloak Admin REST API
keycloak.server-url=http://localhost:8180
keycloak.realm=Nexus3PL
keycloak.admin-client-id=admin-cli
keycloak.admin-username=admin
keycloak.admin-password=admin
# Client ID de l'application dans Keycloak
keycloak.client-id=Nexus3PL-app
keycloak.client-secret=RjRvLjGVkufN6yIRhKCKpSm63VpJYjim

management.endpoints.web.exposure.include=health,info
spring.cloud.consul.discovery.prefer-ip-address=true