# Configuration centrale pour customer-service (Profil DEV)
server.port=8082

# Spring Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/customer_db
spring.datasource.username=postgres
spring.datasource.password=020123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security / OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/Nexus3PL

# Actuator / Management
management.endpoints.web.exposure.include=health,info