# Configuration Minimale (Bootstrap)
spring.application.name=identity-service
spring.profiles.active=dev

# Connexion au Config Service
spring.config.import=optional:configserver:http://localhost:8888

# Discovery
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=identity-service
spring.cloud.consul.discovery.prefer-ip-address=true