# Configuration centrale pour identity-service (Profil DEV)
server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/Nexus3PL

# Configuration Keycloak Admin REST API
keycloak:
  server-url: http://localhost:8180
  realm: Nexus3PL
  admin-username: admin
  admin-password: admin
  client-id: Nexus3PL-app
  client-secret: RjRvLjGVkufN6yIRhKCKpSm63VpJYjim

management:
  endpoints:
    web:
      exposure:
        include: health,info
